name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: dep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          GITHUB: ${{ secrets.GITHUB }}
          LINKEDIN: ${{ secrets.LINKEDIN }}
          MEDIUM_USER: ${{ secrets.MEDIUM_USER }}
          TITLE_PREFIX: ${{ secrets.TITLE_PREFIX }}
          URL: ${{ secrets.URL }}
          EMAIL: ${{ secrets.EMAIL }}
          SECONDARY_EMAIL: ${{ secrets.SECONDARY_EMAIL }}
          META_DESC: ${{ secrets.META_DESC }}
          directory: "."
          file_name: .env
          fail_on_empty: false
      - name: Generate static files
        uses: borales/actions-yarn@v4
        with:
          cmd: generate # will run `yarn build:prod` command

      - name: Move files
        run: mv dist/* /var/www/serhatkaya.comtr
