name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: dep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Make .env file
        run: |
          touch .env
          echo "GITHUB=${{ secrets.GITHUB }}" >> .env
          echo "LINKEDIN=${{ secrets.LINKEDIN }}" >> .env
          echo "MEDIUM_USER=${{ secrets.MEDIUM_USER }}" >> .env
          echo "TITLE_PREFIX=${{ secrets.TITLE_PREFIX }}" >> .env
          echo "URL=${{ secrets.URL }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "SECONDARY_EMAIL=${{ secrets.SECONDARY_EMAIL }}" >> .env
          echo "META_DESC=${{ secrets.META_DESC }}" >> .env

      - name: Generate static files
        uses: borales/actions-yarn@v4
        with:
          cmd: generate # will run `yarn build:prod` command

      - name: Move files
        run: mv dist/* /var/www/skaya.com.tr
